In [1]:
%load_ext watermark
%watermark

2020-10-28T14:17:49+01:00

CPython 3.7.1
IPython 7.2.0

compiler   : MSC v.1915 64 bit (AMD64)
system     : Windows
release    : 10
machine    : AMD64
processor  : AMD64 Family 23 Model 17 Stepping 0, AuthenticAMD
CPU cores  : 8
interpreter: 64bit


In [4]:
# Ejercicios descriptivos con python

import numpy as np # importando numpy
from scipy import stats # importando scipy.stats
import pandas as pd # importando pandas

np.random.seed(123) # para poder replicar el random

In [27]:
# datos normalmente distribuidos
# las primeras son las filas y las segundas las columnas
bdatos = np.random.randn(8,4) 
bdatos

array([[ 0.19381934, -0.25645997, -1.19781651,  1.03824453],
       [ 0.5920923 ,  1.64083463,  0.37554749, -0.38899303],
       [ 0.0644882 ,  0.57983362,  0.80682116,  0.86093965],
       [ 1.61859942, -0.10824915, -2.62841198, -1.15272416],
       [-0.09087315,  1.05250797,  0.51600435, -0.14933894],
       [-0.17655676,  2.20900619, -1.28348837,  0.02068997],
       [-0.84364805,  1.87323105, -0.02632359,  0.70149989],
       [ 0.22891806, -0.86477547,  0.08273405, -0.38140986]])

### Media

In [29]:
# para calcular la media
bdatos.mean() 

0.15333571534665763

In [30]:
# con la fun de numpy
np.mean(bdatos)

0.15333571534665763

In [31]:
# media aritmetica de cada fila
bdatos.mean(axis=1)

array([-0.05555315,  0.55487035,  0.57802066, -0.56769647,  0.33207506,
        0.19241276,  0.42618983, -0.23363331])

In [32]:
# media de cada columna
bdatos.mean(axis=0)

array([ 0.19835492,  0.76574111, -0.41936667,  0.06861351])

### Mediana 

In [33]:
np.median(bdatos)

0.07361112343661483

### Desviación típica / estandar 

In [34]:
 # Desviación típica
np.std(bdatos)

0.9910493234064012

In [35]:
# Desviación estandar por columna
np.std(bdatos, 0)

array([0.66153046, 1.04040088, 1.09826589, 0.70016968])

In [36]:
# varianza
np.var(bdatos) 

0.9821787614242856

### Matriz de correlacion 

In [37]:
np.corrcoef(bdatos)

array([[ 1.        , -0.44285263, -0.07908887,  0.43386984, -0.6230763 ,
         0.24498393,  0.06537661, -0.20313596],
       [-0.44285263,  1.        , -0.35625561,  0.33458619,  0.83445947,
         0.70879991,  0.46457184, -0.4710502 ],
       [-0.07908887, -0.35625561,  1.        , -0.90293531,  0.20134283,
        -0.12120151,  0.50058295, -0.38588386],
       [ 0.43386984,  0.33458619, -0.90293531,  1.        , -0.22746858,
         0.41621748, -0.21681702,  0.05874868],
       [-0.6230763 ,  0.83445947,  0.20134283, -0.22746858,  1.        ,
         0.57140029,  0.69583167, -0.61943963],
       [ 0.24498393,  0.70879991, -0.12120151,  0.41621748,  0.57140029,
         1.        ,  0.79263347, -0.86884905],
       [ 0.06537661,  0.46457184,  0.50058295, -0.21681702,  0.69583167,
         0.79263347,  1.        , -0.98454467],
       [-0.20313596, -0.4710502 , -0.38588386,  0.05874868, -0.61943963,
        -0.86884905, -0.98454467,  1.        ]])

In [39]:
# calculando la correlación entre dos vectores.
np.corrcoef(bdatos[3], bdatos[4])

array([[ 1.        , -0.22746858],
       [-0.22746858,  1.        ]])

In [40]:
# covarianza
np.cov(bdatos) # calcula matriz de covarianza

array([[ 0.86790305, -0.34548572, -0.02677313,  0.72229128, -0.32895891,
         0.33362652,  0.0702133 , -0.09362138],
       [-0.34548572,  0.70124622, -0.10840397,  0.50068039,  0.39600925,
         0.86765344,  0.44848671, -0.19514393],
       [-0.02677313, -0.10840397,  0.13203723, -0.58630304,  0.0414619 ,
        -0.06437891,  0.20969385, -0.06936772],
       [ 0.72229128,  0.50068039, -0.58630304,  3.19326245, -0.23035813,
         1.08723894, -0.44665491,  0.05193595],
       [-0.32895891,  0.39600925,  0.0414619 , -0.23035813,  0.32116606,
         0.47336119,  0.45460106, -0.17366664],
       [ 0.33362652,  0.86765344, -0.06437891,  1.08723894,  0.47336119,
         2.13685348,  1.33573778, -0.62832494],
       [ 0.0702133 ,  0.44848671,  0.20969385, -0.44665491,  0.45460106,
         1.33573778,  1.32899352, -0.5614996 ],
       [-0.09362138, -0.19514393, -0.06936772,  0.05193595, -0.17366664,
        -0.62832494, -0.5614996 ,  0.24474014]])

In [41]:
# covarianza de dos vectores
np.cov(datos[3], datos[4])

array([[ 0.04767826, -0.00888624],
       [-0.00888624,  1.39495179]])

# Pandas 

In [43]:
dataframe = pd.DataFrame(bdatos, index=['a', 'b', 'c', 'd', 'e','f','g','h'], 
                        columns=['colest', 'glucosa', 'trigli', 'leucos'])
dataframe

colest   glucosa    trigli    leucos
a  0.193819 -0.256460 -1.197817  1.038245
b  0.592092  1.640835  0.375547 -0.388993
c  0.064488  0.579834  0.806821  0.860940
d  1.618599 -0.108249 -2.628412 -1.152724
e -0.090873  1.052508  0.516004 -0.149339
f -0.176557  2.209006 -1.283488  0.020690
g -0.843648  1.873231 -0.026324  0.701500
h  0.228918 -0.864775  0.082734 -0.381410

In [44]:
# resumen estadistadistico con pandas
dataframe.describe()

colest   glucosa    trigli    leucos
count  8.000000  8.000000  8.000000  8.000000
mean   0.198355  0.765741 -0.419367  0.068614
std    0.707206  1.112235  1.174096  0.748513
min   -0.843648 -0.864775 -2.628412 -1.152724
25%   -0.112294 -0.145302 -1.219234 -0.383306
50%    0.129154  0.816171  0.028205 -0.064324
75%    0.319712  1.698934  0.410662  0.741360
max    1.618599  2.209006  0.806821  1.038245

In [45]:
# sumando las columnas
dataframe.sum()

colest     1.586839
glucosa    6.125929
trigli    -3.354933
leucos     0.548908
dtype: float64

In [46]:
# sumando filas
dataframe.sum(axis=1)

a   -0.222213
b    2.219481
c    2.312083
d   -2.270786
e    1.328300
f    0.769651
g    1.704759
h   -0.934533
dtype: float64

In [47]:
dataframe.cumsum() # acumulados

colest   glucosa    trigli    leucos
a  0.193819 -0.256460 -1.197817  1.038245
b  0.785912  1.384375 -0.822269  0.649252
c  0.850400  1.964208 -0.015448  1.510191
d  2.468999  1.855959 -2.643860  0.357467
e  2.378126  2.908467 -2.127855  0.208128
f  2.201569  5.117473 -3.411344  0.228818
g  1.357921  6.990704 -3.437667  0.930318
h  1.586839  6.125929 -3.354933  0.548908

In [48]:
# media aritmetica de cada columna con pandas
dataframe.mean()

colest     0.198355
glucosa    0.765741
trigli    -0.419367
leucos     0.068614
dtype: float64

In [49]:
# media aritmetica de cada fila con pandas
dataframe.mean(axis=1)

a   -0.055553
b    0.554870
c    0.578021
d   -0.567696
e    0.332075
f    0.192413
g    0.426190
h   -0.233633
dtype: float64